title: CartPole
description: The inverted pendulum is the God of the motherfxxking world!
author: Towl lynn
avatar: /logo.jpeg
email: towllynn@163.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: ink-machine
  card: summary
logo: logo.jpeg
social:
  name: Towl Lynn
  links:
    - https://twitter.com/ink-machine
    - https://www.facebook.com/ink-machine
    - https://github.com/ink-machine
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
